### ISSUE TITLE
Do a research on UI libraries

### ISSUE THREAD

**Issue by arjun-gautam** [wisteamnepal/wisteam-web#13]
Few UI libraries to compare are Material UI, Semantic UI, Ant Design, Blueprint, Onsen UI, Evergreen
Lets have a light, good looking and user friendly one.

**Comment by CodeDreamerSLS** [comment]
Hi, Here are some search about the above mentioned ui libraries:
Semantic-ui: 
	Weekly download: 1,81,119
	Cons: nested css selector which makes changing custom design & changes difficult
	Pros: No need of other dependencies like css, icons compare to ant & material ui 
	Size: 3.07MB
	Files: 1223
	Total Component: 51

Material-ui: 
	Weekly download: 17,17,627
	Developer: google
	Need core, its icons, css so
	Total Size of core & icons is: 15.81MB (CSS size is not included)
	Total files: 18,234
	found Little bit heavy while changing custom style 
	No frequent updates to solve issues persist	
	Total component: 62 (Lots of feature & some features are going to be added as well in future)

Ant-design:
	Weekly download: 8,15,259 (Its icon is more downloaded than the core package)
	Like material ui, this need some dependencies: core, icons, CSS
	Total Size of core & icons is: 55.9MB (CSS size is not included)
	Though size seems a little higher it is designed well. Many semantic UI users is shifting to this design due to the frequent updates and larger community
	Total component: 63 (Lots of features)

Conclusion: Ant-design, Material-Ui, Semantic-Ui are rich in features.
		However, these days ant-design is more flexible in developing, more components & larger community compared to the other two material-UI, semantic-UI.
		I appreciate all these 3 rich libraries & is under my choice than the others.

OnsenUI: 
	New and is under development
	WeeklyDownload: 997
	Size: 887KB
	TotalFiles: 62
	TotalComponents: 25 (which is minuscule component, May be the future version will be improved)

Evergreen:
	This is also a new UI library but found prettier & found future compared to OnsenUI
	WeeklyDownload: 7,070
	Size: 11.9MB
	TotalFiles: 1,937
	TotalComponents: 33 (this is also a minuscule amount, future version is welcomed)

**Comment by arjun-gautam** [comment]
Great insight. I also checked the components of Ant design. The components are simple and sleeky. The components looks and works better than Material UI. Lets use Ant Design.
