### ISSUE TITLE
Start development for User Interface

### ISSUE THREAD

**Issue by arjun-gautam** [wisteamnepal/wisteam-web#19]
Design reference @ https://www.figma.com/file/rEnp3VTnzAprgu17UYnX15/WiSTEAM-Website?node-id=0%3A1

- [ ] Homepage
- [ ] About page
- [ ] Donate page
- [ ] Contacr page
- [ ] Blog page

**Comment by arjun-gautam** [comment]
@CodeDreamerSLS Start with homepage. Other pages are in the process of design

**Comment by CodeDreamerSLS** [comment]
@arjun-gautam Just pushed the navigation bar of homepage

**Comment by arjun-gautam** [comment]
Closing because there are more descriptive issue for this tasks now.
