### ISSUE TITLE
Develop Resource Page

### ISSUE THREAD

**Issue by arjun-gautam** [wisteamnepal/wisteam-web#46]
**Components**
Common component

- [x] Internal menu
- [x] Pinned resources list (title, image, date, short description and downloadable file)

Report List Page

- [x] Report short info (Date, title, description and button)
- [x] Pagination

Report Brief Page
- [x] Pinned Resource
- [x] Main content (content, downloadable file)

Toolkit List Page

- [x] Toolkit short info (Date, title, description and button)
- [x] Pagination

Toolkit Brief Page
- [x] Pinned Resource
- [x] Main content (content, downloadable file)

Policies List Page

- [x] Policy short info (Date, title, description and button)
- [x] Pagination

Policy Brief Page
- [x] Pinned Resource
- [x] Main content (content, downloadable file)

**Comment by CodeDreamerSLS** [comment]
Resource List page done
