### ISSUE TITLE
Develop impact stories page

### ISSUE THREAD

**Issue by arjun-gautam** [wisteamnepal/wisteam-web#47]
**components**
List page
- [x] Title
- [x] Cards (Title, short description, avatar, date and name)
- [x] pagination

Brief page

- [x] Date
- [x] Title
- [x] Banner Image
- [x] Description
- [x] Writer info
- [x] Next and Previous button
- [x] Claps
- [x] Social Media share
- [x] Comment Area

**Comment by CodeDreamerSLS** [comment]
comment interactive part left
