### ISSUE TITLE
Develop About us section

### ISSUE THREAD

**Issue by arjun-gautam** [wisteamnepal/wisteam-web#49]
**Components**

Common Component

- [x] Internal menu

About page

- [x] Title
- [x] photo
- [x] description

Our impact page

- [x] Title
- [x] photo
- [x] description

Our policies page

- [x] Title
- [x] description

Our team page

- [x] Pinned team member
- [x] Team group
- [x] Member items in each team group

Our partner page

- [x] Organization Info list

**Comment by CodeDreamerSLS** [comment]
done
